### ISSUE TITLE
Decal projection onto Terrain

### ISSUE THREAD

**Issue by ohbado** [CyberAgentGameEntertainment/AirSticker#20]
Hello.
I think Air Sticker is a great feature.

By the way, it appears that Air Sticker does not support decal projection on Terrain.
Are there any plans to support Terrain in the future?

**Comment by CyTakayukiKiyohara** [comment]
Thank you for reporting the Issue.
As reported, AirSticker is not compatible with Terrain.
We will check if we can support it and if so, we will do so, so please wait a little longer.

**Comment by CyTakayukiKiyohara** [comment]
Decals on terrain were found to be feasible and will be released as a new feature in the near future.

**Comment by ohbado** [comment]
Thank you!
I look forward to the support for Terrain.
